name:           titlecase
version:        "1.0.1"
synopsis:       Convert English Words to Title Case
author:
  - Nikita Karetnikov
  - Peter Simons
  - Aaron Wolf
  - Serg Nesterov
maintainer:     Peter Simons <simons@cryp.to>
license:        BSD3
license-file:   LICENSE
github:         peti/titlecase
category:       Text
stability:      stable
tested-with:    GHC > 7.6 && < 8.1
description:    Capitalize all English words except articles (a, an, the),
                coordinating conjunctions (for, and, nor, but, or, yet, so), and
                prepositions (unless they begin or end the title).  The
                prepositions are taken from
                <https://en.wikipedia.org/wiki/List_of_English_prepositions Wikipedia>.
ghc-options:    -Wall

dependencies:
  - base <5

library:
  source-dirs:          src
  exposed-modules:
    - Data.Text.Titlecase
    - Data.Text.Titlecase.Internal
  other-extensions:
    - MultiWayIf

executables:
  titlecase:
    main:               Main.hs
    dependencies:
      - titlecase

tests:
  test:
    main:               Main.hs
    source-dirs:        tests
    dependencies:
      - titlecase
      - tasty
      - tasty-hunit
      - tasty-quickcheck
